--[[
Releases:
* 2.3.2.0

Version:
* 2.2.0.0

Rewrite by Richard Fontaine "RIRI", June 2026.
--]]
function LC_Get_Object(Construct_Pool)
    local MacroObject    = Root().ShowData.DataPools[Construct_Pool].Macros
    local SequenceObject = Root().ShowData.DataPools[Construct_Pool].Sequences
    local Layout_Object  = Root().ShowData.DataPools[Construct_Pool].Layouts
    local Nr
    return MacroObject, SequenceObject, Layout_Object, Nr
end

function Create_Macro_Reset(CurrentMacroNr, prefix, surfix, MatrickNrStart, a, CurrentSeqNr, First_Id_Lay, TLayNr,
                            Fade_Element, Delay_F_Element, Delay_T_Element, Phase_Element, Group_Element, Block_Element,
                            Wings_Element, MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)


    LC_Check_Size_Pool(CurrentMacroNr + 1, MacroObject)
    MacroObject:Create(CurrentMacroNr + 1)
    MacroObject[CurrentMacroNr + 1]:Set('Name', "'" .. prefix .. surfix[a] .. "_Reset'")
    for b = 1, 72 do
        MacroObject[CurrentMacroNr + 1]:Insert(b)
    end
    MacroObject[CurrentMacroNr + 1][1]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][2]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][3]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][4]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][5]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][6]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '" None')
    MacroObject[CurrentMacroNr + 1][7]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" None')
    MacroObject[CurrentMacroNr + 1][8]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" None')
    MacroObject[CurrentMacroNr + 1][9]:Set('Command', 'Set DataPool ' ..
        Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" None')
    MacroObject[CurrentMacroNr + 1][10]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 1] .. ' Thru ' .. First_Id_Lay[a + 1] + 4)
    MacroObject[CurrentMacroNr + 1][11]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 5] .. ' Thru ' .. First_Id_Lay[a + 5] + 4)
    MacroObject[CurrentMacroNr + 1][12]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 9] .. ' Thru ' .. First_Id_Lay[a + 9] + 4)
    MacroObject[CurrentMacroNr + 1][13]:Set('Command',
        'Off DataPool ' .. Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 13])
    MacroObject[CurrentMacroNr + 1][14]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 17] .. ' Thru ' .. First_Id_Lay[a + 17] + 4)
    MacroObject[CurrentMacroNr + 1][15]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 21] .. ' Thru ' .. First_Id_Lay[a + 21] + 4)
    MacroObject[CurrentMacroNr + 1][16]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 25] .. ' Thru ' .. First_Id_Lay[a + 25] + 4)
    MacroObject[CurrentMacroNr + 1][17]:Set('Command',
        'Off DataPool ' .. Construct_Pool .. ' Sequence ' .. CurrentSeqNr + 1)
    MacroObject[CurrentMacroNr + 1][18]:Set('Command', 'SetUserVariable "LC_Fonction" 1')
    MacroObject[CurrentMacroNr + 1][19]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][20]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][21]:Set('Command', 'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    MacroObject[CurrentMacroNr + 1][22]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][23]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][24]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][25]:Set('Command', 'SetUserVariable "LC_Fonction" 2')
    MacroObject[CurrentMacroNr + 1][26]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][27]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][28]:Set('Command', 'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    MacroObject[CurrentMacroNr + 1][29]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][30]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][31]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][32]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][33]:Set('Command', 'SetUserVariable "LC_Fonction" 3')
    MacroObject[CurrentMacroNr + 1][34]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][35]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][36]:Set('Command', 'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    MacroObject[CurrentMacroNr + 1][37]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][38]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][39]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][40]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][41]:Set('Command', 'SetUserVariable "LC_Fonction" 4')
    MacroObject[CurrentMacroNr + 1][42]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][43]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][44]:Set('Command', 'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    MacroObject[CurrentMacroNr + 1][45]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][46]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][47]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][48]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][49]:Set('Command', 'SetUserVariable "LC_Fonction" 5')
    MacroObject[CurrentMacroNr + 1][50]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][51]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][52]:Set('Command', 'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    MacroObject[CurrentMacroNr + 1][53]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][54]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][55]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][56]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][57]:Set('Command', 'SetUserVariable "LC_Fonction" 6')
    MacroObject[CurrentMacroNr + 1][58]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][59]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][60]:Set('Command', 'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    MacroObject[CurrentMacroNr + 1][61]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][62]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][63]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][64]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr + 1][65]:Set('Command', 'SetUserVariable "LC_Fonction" 7')
    MacroObject[CurrentMacroNr + 1][66]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr + 1][67]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr + 1][68]:Set('Command', 'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    MacroObject[CurrentMacroNr + 1][69]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr + 1][70]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr + 1][71]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr + 1][72]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')



    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr + 1 .. ' \'' .. prefix .. surfix[a] .. '_Reset\'')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr + 1 .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 2 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 3 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 4 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 5 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 6 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 7 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 8 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 9 Command=\'Set DataPool ' ..
    --     Construct_Pool .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" None')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 10 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 1] .. ' Thru ' .. First_Id_Lay[a + 1] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 11 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 5] .. ' Thru ' .. First_Id_Lay[a + 5] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 12 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 9] .. ' Thru ' .. First_Id_Lay[a + 9] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 13 Command=\'Off DataPool ' .. Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 13])
    -- Cmd('Insert')
    -- CmdIndirectWait('set 14 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 17] .. ' Thru ' .. First_Id_Lay[a + 17] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 15 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 21] .. ' Thru ' .. First_Id_Lay[a + 21] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 16 Command=\'Off DataPool ' ..
    --     Construct_Pool .. ' Sequence ' .. First_Id_Lay[a + 25] .. ' Thru ' .. First_Id_Lay[a + 25] + 4)
    -- Cmd('Insert')
    -- CmdIndirectWait('set 17 Command=\'Off DataPool ' .. Construct_Pool .. ' Sequence ' .. CurrentSeqNr + 1)
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 18 Command=\'SetUserVariable "LC_Fonction" 1')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 19 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 20 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 21 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 22 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 23 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 24 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 25 Command=\'SetUserVariable "LC_Fonction" 2')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 26 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 27 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 28 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 29 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 30 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 31 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 32 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 33 Command=\'SetUserVariable "LC_Fonction" 3')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 34 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 36 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 38 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 39 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 40 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 41 Command=\'SetUserVariable "LC_Fonction" 4')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 42 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 43 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 44 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 45 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 46 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 47 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 48 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 49 Command=\'SetUserVariable "LC_Fonction" 5')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 50 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 51 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 52 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 53 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 54 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 55 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 56 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 57 Command=\'SetUserVariable "LC_Fonction" 6')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 58 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 59 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 60 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 61 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 62 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 63 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 64 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 65 Command=\'SetUserVariable "LC_Fonction" 7')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 66 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 67 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 68 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 69 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 70 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 71 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 72 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end -- end function Create_Macro_Reset(...)

function Create_Macro_Delay_From(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr,
                                 LayNr, MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'DelayFrom Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '"')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayFrom Input' .. surfix[a] .. '"')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Delay_To(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                               MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'DelayTo Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '"')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayTo Input' .. surfix[a] .. '"')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Phase(CurrentMacroNr, prefix, surfix, a, MatrickNrStart, fonct, TLayNr, LayNr, MatrickNr,
                            Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'Phase Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '"')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '"')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Phase Input' .. surfix[a] .. "'")
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Group(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'Group Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" ')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Group Input' .. surfix[a] .. '"')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" ')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Block(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'Block Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" ')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Block Input' .. surfix[a] .. '"')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" ')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Wings(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. 'Wings Input' .. surfix[a] .. "'")
    for b = 1, 10 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
        Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Edit DataPool ' ..
        Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" ')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Element" ' .. LayNr .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Wings Input' .. surfix[a] .. '"')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
    --     Construct_Pool .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" ')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Fade_E(CurrentMacroNr, prefix, Argument_Fade, i, surfix, a, FirstSeqTime, LastSeqTime, CurrentSeqNr,
                             SeqNrStart, SeqNrEnd, MatrickNrStart, TLayNr, Fade_Element, Construct_Pool, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)
    LC_Check_Size_Pool(CurrentMacroNr, MacroObject)
    MacroObject:Create(CurrentMacroNr)
    MacroObject[CurrentMacroNr]:Set('Name', "'" .. prefix .. Argument_Fade[i].name .. surfix[a] .. "'")
    for b = 1, 11 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end
    MacroObject[CurrentMacroNr][1]:Set('Command', '')
    -- MacroObject[CurrentMacroNr][1]:Set('Command', 'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeqTime .. ' thru ' .. LastSeqTime .. ' - ' .. CurrentSeqNr .. '')
    MacroObject[CurrentMacroNr][2]:Set('Command', 'Set DataPool ' .. Construct_Pool .. '  Sequence ' ..
        SeqNrStart .. ' thru ' .. SeqNrEnd .. ' UseExecutorTime=' .. Argument_Fade[i].UseExTime .. '')
    MacroObject[CurrentMacroNr][3]:Set('Command', 'Set DataPool ' .. Construct_Pool .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    MacroObject[CurrentMacroNr][4]:Set('Command', 'Set DataPool ' .. Construct_Pool .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    MacroObject[CurrentMacroNr][5]:Set('Command', 'SetUserVariable "LC_Fonction" 1')
    MacroObject[CurrentMacroNr][6]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][7]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][8]:Set('Command', 'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    MacroObject[CurrentMacroNr][9]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][10]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][11]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    CurrentMacroNr = CurrentMacroNr + 1
    return CurrentMacroNr
    -- CmdIndirectWait('Store Macro ' ..
    --     CurrentMacroNr + i - 1 .. ' \'' .. prefix .. Argument_Fade[i].name .. surfix[a] .. '')
    -- CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr + i - 1 .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set  1 Command=\'Off DataPool ' ..
    --     Construct_Pool .. '  Sequence ' .. FirstSeqTime .. ' thru ' .. LastSeqTime .. ' - ' .. CurrentSeqNr .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set  2 Command=\'Set DataPool ' .. Construct_Pool .. '  Sequence ' ..
    --     SeqNrStart .. ' thru ' .. SeqNrEnd .. ' UseExecutorTime=' .. Argument_Fade[i].UseExTime .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set  3 Command=\'Set DataPool ' .. Construct_Pool .. ' Matricks   ' ..
    --     MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    -- Cmd('Insert')
    -- CmdIndirectWait('set  4 Command=\'Set DataPool ' .. Construct_Pool .. ' Matricks   ' ..
    --     MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Fonction" 1')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 10 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 11 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait('ChangeDestination Root')
end

function Add_Macro_Call(a, TLayNr, Fade_Element, MatrickNrStart, Delay_F_Element, Delay_T_Element, Phase_Element,
                        Group_Element, Block_Element, Wings_Element, Construct_Pool, CurrentMacroNr, Call_Pool)
    local MacroObject, SequenceObject, Layout_Object, Nr = LC_Get_Object(Construct_Pool)

    for b = 33, 81 do
        MacroObject[CurrentMacroNr]:Insert(b)
    end

    MacroObject[CurrentMacroNr][33]:Set('Command', 'SetUserVariable "LC_Fonction" 1')
    MacroObject[CurrentMacroNr][34]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][35]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][36]:Set('Command', 'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    MacroObject[CurrentMacroNr][37]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][38]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][39]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][40]:Set('Command', 'SetUserVariable "LC_Fonction" 2')
    MacroObject[CurrentMacroNr][41]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][42]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][43]:Set('Command', 'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    MacroObject[CurrentMacroNr][44]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][45]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][46]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][47]:Set('Command', 'SetUserVariable "LC_Fonction" 3')
    MacroObject[CurrentMacroNr][48]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][49]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][50]:Set('Command', 'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    MacroObject[CurrentMacroNr][51]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][52]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][53]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][54]:Set('Command', 'SetUserVariable "LC_Fonction" 4')
    MacroObject[CurrentMacroNr][55]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][56]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][57]:Set('Command', 'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    MacroObject[CurrentMacroNr][58]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][59]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][60]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][61]:Set('Command', 'SetUserVariable "LC_Fonction" 5')
    MacroObject[CurrentMacroNr][62]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][63]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][64]:Set('Command', 'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    MacroObject[CurrentMacroNr][65]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][66]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][67]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][68]:Set('Command', 'SetUserVariable "LC_Fonction" 6')
    MacroObject[CurrentMacroNr][69]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][70]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][71]:Set('Command', 'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    MacroObject[CurrentMacroNr][72]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][73]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][74]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')
    MacroObject[CurrentMacroNr][75]:Set('Command', 'SetUserVariable "LC_Fonction" 7')
    MacroObject[CurrentMacroNr][76]:Set('Command', 'SetUserVariable "LC_Axes" ' .. a .. '')
    MacroObject[CurrentMacroNr][77]:Set('Command', 'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    MacroObject[CurrentMacroNr][78]:Set('Command', 'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    MacroObject[CurrentMacroNr][79]:Set('Command', 'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    MacroObject[CurrentMacroNr][80]:Set('Command', 'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    MacroObject[CurrentMacroNr][81]:Set('Command', 'Call ' .. Call_Pool .. ' Plugin "DEV_LC_View"')

    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 33 Command=\'SetUserVariable "LC_Fonction" 1')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 34 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 36 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 38 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 39 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 40 Command=\'SetUserVariable "LC_Fonction" 2')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 41 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 42 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 43 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 44 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 45 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 46 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 47 Command=\'SetUserVariable "LC_Fonction" 3')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 48 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 49 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 50 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 51 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 52 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 53 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 54 Command=\'SetUserVariable "LC_Fonction" 4')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 55 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 56 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 57 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 58 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 59 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 60 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 61 Command=\'SetUserVariable "LC_Fonction" 5')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 62 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 63 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 64 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 65 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 66 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 67 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 68 Command=\'SetUserVariable "LC_Fonction" 6')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 69 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 70 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 71 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 72 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 73 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 74 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 75 Command=\'SetUserVariable "LC_Fonction" 7')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 76 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 77 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 78 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 79 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 80 Command=\'SetUserVariable "LC_DataPool" ' .. Construct_Pool .. '')
    -- CmdIndirectWait("Insert")
    -- CmdIndirectWait('set 81 Command=\'Call DataPool ' .. Construct_Pool .. ' Plugin "LC_View"')
end

--end LC_Macro_Cmd.lua
