--[[
    Releases:
    * 2.0.0.8

    Created by Richard Fontaine "RIRI", April 2024.
    --]]

function Create_Macro_Reset(CurrentMacroNr, prefix, surfix, MatrickNrStart, a, CurrentSeqNr, First_Id_Lay, TLayNr,
                            Fade_Element, Delay_F_Element, Delay_T_Element, Phase_Element, Group_Element, Block_Element,
                            Wings_Element, MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr + 1 .. ' \'' .. prefix .. surfix[a] .. '_Reset\'')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr + 1 .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 2 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 3 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 4 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 5 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 6 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '" None')
    Cmd('Insert')
    Cmd('set 7 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" None')
    Cmd('Insert')
    Cmd('set 8 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" None')
    Cmd('Insert')
    Cmd('set 9 Command=\'Set DataPool ' ..
    Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" None')
    Cmd('Insert')
    Cmd('set 10 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 1] .. ' Thru ' .. First_Id_Lay[a + 1] + 4)
    Cmd('Insert')
    Cmd('set 11 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 5] .. ' Thru ' .. First_Id_Lay[a + 5] + 4)
    Cmd('Insert')
    Cmd('set 12 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 9] .. ' Thru ' .. First_Id_Lay[a + 9] + 4)
    Cmd('Insert')
    Cmd('set 13 Command=\'Off DataPool ' .. Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 13])
    Cmd('Insert')
    Cmd('set 14 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 17] .. ' Thru ' .. First_Id_Lay[a + 17] + 4)
    Cmd('Insert')
    Cmd('set 15 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 21] .. ' Thru ' .. First_Id_Lay[a + 21] + 4)
    Cmd('Insert')
    Cmd('set 16 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 25] .. ' Thru ' .. First_Id_Lay[a + 25] + 4)
    Cmd('Insert')
    Cmd('set 17 Command=\'Off DataPool ' .. Data_Pool_Nr .. ' Sequence ' .. CurrentSeqNr + 1)
    Cmd("Insert")
    Cmd('set 18 Command=\'SetUserVariable "LC_Fonction" 1')
    Cmd("Insert")
    Cmd('set 19 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 20 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 21 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    Cmd("Insert")
    Cmd('set 22 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 23 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 24 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 25 Command=\'SetUserVariable "LC_Fonction" 2')
    Cmd("Insert")
    Cmd('set 26 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 27 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 28 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    Cmd("Insert")
    Cmd('set 29 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 30 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 31 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 32 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 33 Command=\'SetUserVariable "LC_Fonction" 3')
    Cmd("Insert")
    Cmd('set 34 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 36 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    Cmd("Insert")
    Cmd('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 38 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 39 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 40 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 41 Command=\'SetUserVariable "LC_Fonction" 4')
    Cmd("Insert")
    Cmd('set 45 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 43 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 44 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    Cmd("Insert")
    Cmd('set 45 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 46 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 47 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 48 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 49 Command=\'SetUserVariable "LC_Fonction" 5')
    Cmd("Insert")
    Cmd('set 50 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 51 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 52 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    Cmd("Insert")
    Cmd('set 53 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 54 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 55 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 56 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 57 Command=\'SetUserVariable "LC_Fonction" 6')
    Cmd("Insert")
    Cmd('set 58 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 59 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 60 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    Cmd("Insert")
    Cmd('set 61 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 62 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 63 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 64 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 65 Command=\'SetUserVariable "LC_Fonction" 7')
    Cmd("Insert")
    Cmd('set 66 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 67 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 68 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    Cmd("Insert")
    Cmd('set 69 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 70 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 71 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 72 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end -- end function Create_Macro_Reset(...)

function Create_Macro_Delay_From(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr,
                                 LayNr, MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayFrom Input\'' .. surfix[a] .. '"')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    Cmd("Insert")
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '"')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Delay_To(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                               MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayTo Input\'' .. surfix[a] .. '"')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    Cmd("Insert")
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '"')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Phase(CurrentMacroNr, prefix, surfix, a, MatrickNrStart, fonct, TLayNr, LayNr, MatrickNr,
                            Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Phase Input\'' .. surfix[a] .. "'")
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '"')
    Cmd("Insert")
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '"')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Group(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Group Input\'' .. surfix[a] .. '"')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    Cmd('Insert')
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" ')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Block(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Block Input\'' .. surfix[a] .. '"')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    Cmd('Insert')
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" ')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Wings(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Wings Input' .. surfix[a] .. '"')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr .. '')
    Cmd('Insert')
    Cmd('set 1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    Cmd('Insert')
    Cmd('set 2 Command=\'Edit DataPool ' ..
    Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" ')
    Cmd("Insert")
    Cmd('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    Cmd("Insert")
    Cmd('set 4 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Create_Macro_Fade_E(CurrentMacroNr, prefix, Argument_Fade, i, surfix, a, FirstSeqTime, LastSeqTime, CurrentSeqNr,
                             SeqNrStart, SeqNrEnd, MatrickNrStart, TLayNr, Fade_Element, Data_Pool_Nr)
    Cmd('Store Macro ' .. CurrentMacroNr + i - 1 .. ' \'' .. prefix .. Argument_Fade[i].name .. surfix[a] .. '')
    Cmd('ChangeDestination Macro ' .. CurrentMacroNr + i - 1 .. '')
    Cmd('Insert')
    Cmd('set  1 Command=\'Off DataPool ' ..
    Data_Pool_Nr .. '  Sequence ' .. FirstSeqTime .. ' thru ' .. LastSeqTime .. ' - ' .. CurrentSeqNr .. '')
    Cmd('Insert')
    Cmd('set  2 Command=\'Set DataPool ' .. Data_Pool_Nr .. '  Sequence ' ..
        SeqNrStart .. ' thru ' .. SeqNrEnd .. ' UseExecutorTime=' .. Argument_Fade[i].UseExTime .. '')
    Cmd('Insert')
    Cmd('set  3 Command=\'Set DataPool ' .. Data_Pool_Nr .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    Cmd('Insert')
    Cmd('set  4 Command=\'Set DataPool ' .. Data_Pool_Nr .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    Cmd("Insert")
    Cmd('set 5 Command=\'SetUserVariable "LC_Fonction" 1')
    Cmd("Insert")
    Cmd('set 6 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 7 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 8 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    Cmd("Insert")
    Cmd('set 9 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 10 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 11 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd('ChangeDestination Root')
end

function Add_Macro_Call(a, TLayNr, Fade_Element, MatrickNrStart, Delay_F_Element, Delay_T_Element, Phase_Element,
                        Group_Element, Block_Element, Wings_Element, Data_Pool_Nr)
    Cmd("Insert")
    Cmd('set 33 Command=\'SetUserVariable "LC_Fonction" 1')
    Cmd("Insert")
    Cmd('set 34 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 36 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    Cmd("Insert")
    Cmd('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 38 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 39 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 40 Command=\'SetUserVariable "LC_Fonction" 2')
    Cmd("Insert")
    Cmd('set 41 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 42 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 43 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    Cmd("Insert")
    Cmd('set 44 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 45 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 46 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 47 Command=\'SetUserVariable "LC_Fonction" 3')
    Cmd("Insert")
    Cmd('set 48 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 49 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 50 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    Cmd("Insert")
    Cmd('set 51 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 52 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 53 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 54 Command=\'SetUserVariable "LC_Fonction" 4')
    Cmd("Insert")
    Cmd('set 55 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 56 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 57 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    Cmd("Insert")
    Cmd('set 58 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 59 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 60 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 61 Command=\'SetUserVariable "LC_Fonction" 5')
    Cmd("Insert")
    Cmd('set 62 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 63 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 64 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    Cmd("Insert")
    Cmd('set 65 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 66 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 67 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 68 Command=\'SetUserVariable "LC_Fonction" 6')
    Cmd("Insert")
    Cmd('set 69 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 70 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 71 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    Cmd("Insert")
    Cmd('set 72 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 73 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 74 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    Cmd("Insert")
    Cmd('set 75 Command=\'SetUserVariable "LC_Fonction" 7')
    Cmd("Insert")
    Cmd('set 76 Command=\'SetUserVariable "LC_Axes" "' .. a .. '"')
    Cmd("Insert")
    Cmd('set 77 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    Cmd("Insert")
    Cmd('set 78 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    Cmd("Insert")
    Cmd('set 79 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    Cmd("Insert")
    Cmd('set 80 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    Cmd("Insert")
    Cmd('set 81 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
end

--end LC_Macro_Cmd.lua
