--[[
    Releases:
    * 2.3.1.1

    Created by Richard Fontaine "RIRI", September 2025.
    --]]

function Create_Macro_Reset(CurrentMacroNr, prefix, surfix, MatrickNrStart, a, CurrentSeqNr, First_Id_Lay, TLayNr,
                            Fade_Element, Delay_F_Element, Delay_T_Element, Phase_Element, Group_Element, Block_Element,
                            Wings_Element, MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr + 1 .. ' \'' .. prefix .. surfix[a] .. '_Reset\'')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr + 1 .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 2 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 3 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 4 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 5 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 6 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '" None')
   Cmd('Insert')
    CmdIndirectWait('set 7 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" None')
   Cmd('Insert')
    CmdIndirectWait('set 8 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" None')
   Cmd('Insert')
    CmdIndirectWait('set 9 Command=\'Set DataPool ' ..
        Data_Pool_Nr .. '  Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" None')
   Cmd('Insert')
    CmdIndirectWait('set 10 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 1] .. ' Thru ' .. First_Id_Lay[a + 1] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 11 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 5] .. ' Thru ' .. First_Id_Lay[a + 5] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 12 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 9] .. ' Thru ' .. First_Id_Lay[a + 9] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 13 Command=\'Off DataPool ' .. Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 13])
   Cmd('Insert')
    CmdIndirectWait('set 14 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 17] .. ' Thru ' .. First_Id_Lay[a + 17] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 15 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 21] .. ' Thru ' .. First_Id_Lay[a + 21] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 16 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. ' Sequence ' .. First_Id_Lay[a + 25] .. ' Thru ' .. First_Id_Lay[a + 25] + 4)
   Cmd('Insert')
    CmdIndirectWait('set 17 Command=\'Off DataPool ' .. Data_Pool_Nr .. ' Sequence ' .. CurrentSeqNr + 1)
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 18 Command=\'SetUserVariable "LC_Fonction" 1')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 19 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 20 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 21 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 22 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 23 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 24 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 25 Command=\'SetUserVariable "LC_Fonction" 2')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 26 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 27 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 28 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 29 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 30 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 31 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 32 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 33 Command=\'SetUserVariable "LC_Fonction" 3')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 34 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 36 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 38 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 39 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 40 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 41 Command=\'SetUserVariable "LC_Fonction" 4')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 42 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 43 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 44 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 45 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 46 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 47 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 48 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 49 Command=\'SetUserVariable "LC_Fonction" 5')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 50 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 51 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 52 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 53 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 54 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 55 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 56 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 57 Command=\'SetUserVariable "LC_Fonction" 6')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 58 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 59 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 60 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 61 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 62 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 63 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 64 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 65 Command=\'SetUserVariable "LC_Fonction" 7')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 66 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 67 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 68 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 69 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 70 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 71 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 72 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end -- end function Create_Macro_Reset(...)

function Create_Macro_Delay_From(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr,
                                 LayNr, MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayFrom Input' .. surfix[a] .. '"')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayFrom' .. surfix[a] .. '"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Delay_To(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                               MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'DelayTo Input' .. surfix[a] .. '"')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "DelayTo' .. surfix[a] .. '"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Phase(CurrentMacroNr, prefix, surfix, a, MatrickNrStart, fonct, TLayNr, LayNr, MatrickNr,
                            Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Phase Input' .. surfix[a] .. "'")
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseFrom' .. surfix[a] .. '"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "PhaseTo' .. surfix[a] .. '"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Group(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Group Input' .. surfix[a] .. '"')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
   Cmd('Insert')
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Group" ')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Block(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Block Input' .. surfix[a] .. '"')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
   Cmd('Insert')
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Block" ')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Wings(CurrentMacroNr, prefix, surfix, a, FirstSeq, LastSeq, MatrickNrStart, fonct, TLayNr, LayNr,
                            MatrickNr, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr .. ' \'' .. prefix .. 'Wings Input' .. surfix[a] .. '"')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set 1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeq .. ' thru ' .. LastSeq .. ' - ' .. LastSeq .. '')
   Cmd('Insert')
    CmdIndirectWait('set 2 Command=\'Edit DataPool ' ..
        Data_Pool_Nr .. ' Matricks ' .. MatrickNrStart .. ' Property "' .. surfix[a] .. 'Wings" ')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 3 Command=\'SetUserVariable "LC_Fonction" ' .. fonct .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 4 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Element" ' .. LayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Matrick_Thru" ' .. MatrickNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Create_Macro_Fade_E(CurrentMacroNr, prefix, Argument_Fade, i, surfix, a, FirstSeqTime, LastSeqTime, CurrentSeqNr,
                             SeqNrStart, SeqNrEnd, MatrickNrStart, TLayNr, Fade_Element, Data_Pool_Nr)
    CmdIndirectWait('Store Macro ' .. CurrentMacroNr + i - 1 .. ' \'' .. prefix .. Argument_Fade[i].name .. surfix[a] .. '')
    CmdIndirectWait('ChangeDestination Macro ' .. CurrentMacroNr + i - 1 .. '')
   Cmd('Insert')
    CmdIndirectWait('set  1 Command=\'Off DataPool ' ..
        Data_Pool_Nr .. '  Sequence ' .. FirstSeqTime .. ' thru ' .. LastSeqTime .. ' - ' .. CurrentSeqNr .. '')
   Cmd('Insert')
    CmdIndirectWait('set  2 Command=\'Set DataPool ' .. Data_Pool_Nr .. '  Sequence ' ..
        SeqNrStart .. ' thru ' .. SeqNrEnd .. ' UseExecutorTime=' .. Argument_Fade[i].UseExTime .. '')
   Cmd('Insert')
    CmdIndirectWait('set  3 Command=\'Set DataPool ' .. Data_Pool_Nr .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeFrom' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
   Cmd('Insert')
    CmdIndirectWait('set  4 Command=\'Set DataPool ' .. Data_Pool_Nr .. ' Matricks   ' ..
        MatrickNrStart .. ' Property "FadeTo' .. surfix[a] .. '" ' .. Argument_Fade[i].Time .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 5 Command=\'SetUserVariable "LC_Fonction" 1')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 6 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 7 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 8 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 9 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 10 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 11 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait('ChangeDestination Root')
end

function Add_Macro_Call(a, TLayNr, Fade_Element, MatrickNrStart, Delay_F_Element, Delay_T_Element, Phase_Element,
                        Group_Element, Block_Element, Wings_Element, Data_Pool_Nr)
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 33 Command=\'SetUserVariable "LC_Fonction" 1')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 34 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 35 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 36 Command=\'SetUserVariable "LC_Element" ' .. Fade_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 37 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 38 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 39 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 40 Command=\'SetUserVariable "LC_Fonction" 2')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 41 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 42 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 43 Command=\'SetUserVariable "LC_Element" ' .. Delay_F_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 44 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 45 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 46 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 47 Command=\'SetUserVariable "LC_Fonction" 3')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 48 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 49 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 50 Command=\'SetUserVariable "LC_Element" ' .. Delay_T_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 51 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 52 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 53 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 54 Command=\'SetUserVariable "LC_Fonction" 4')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 55 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 56 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 57 Command=\'SetUserVariable "LC_Element" ' .. Phase_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 58 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 59 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 60 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 61 Command=\'SetUserVariable "LC_Fonction" 5')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 62 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 63 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 64 Command=\'SetUserVariable "LC_Element" ' .. Group_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 65 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 66 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 67 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 68 Command=\'SetUserVariable "LC_Fonction" 6')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 69 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 70 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 71 Command=\'SetUserVariable "LC_Element" ' .. Block_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 72 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 73 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 74 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 75 Command=\'SetUserVariable "LC_Fonction" 7')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 76 Command=\'SetUserVariable "LC_Axes" ' .. a .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 77 Command=\'SetUserVariable "LC_Layout" ' .. TLayNr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 78 Command=\'SetUserVariable "LC_Element" ' .. Wings_Element .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 79 Command=\'SetUserVariable "LC_Matrick" ' .. MatrickNrStart .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 80 Command=\'SetUserVariable "LC_DataPool" ' .. Data_Pool_Nr .. '')
    CmdIndirectWait("Insert")
    CmdIndirectWait('set 81 Command=\'Call DataPool ' .. Data_Pool_Nr .. ' Plugin "LC_View"')
end

--end LC_Macro_Cmd.lua
